version: '3.5'

services:
  db:
    image: postgres:latest
    container_name: psql-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=sport_stats
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - './db/init:/docker-entrypoint-initdb.d/'
  app:
    container_name: flask-react-app
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./server:/usr/src/app/server
      - ./client:/usr/src/app/client
      - '/usr/src/app/node_modules'
    depends_on:
      - "db"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - HOST_URL=http://192.168.99.100:5000
